version: '3.5'

services:
  db-ingestion-1:
    image: mysql:8.0
    container_name: db-ingestion-1
    restart: always
    environment:
      MYSQL_DATABASE: 'db_ingestion_1'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'